### ISSUE TITLE
Summary 기능 test

### ISSUE THREAD

**Issue by jerry-1211** [vemo-kj/vemo#19]
### 💼 작업 설명

유튜브 자막 가져와서 AI 요약
### ✅ To-do

- [x] 유튜브 자막  & 타임스탬프 가져오기 
- [x] Open AI API 사용해서 스크립트 요약 
- [x] 퀴즈 프롬프트 설정

**Comment by jerry-1211** [comment]
2단계로 프롬프트 학습하여 정확도는 높아졌습니다.

**Comment by jerry-1211** [comment]
지금은 자막 추출 & 요약이 하나의 API(subtitles)에 있습니다.
추후 필요하면 분리해서 응답할 수 있게 만들게요 🍕
