### ISSUE TITLE
✨ Feat: Vemo editor 수정

### ISSUE THREAD

**Issue by daniely7** [vemo-kj/vemo#33]
### 💼 작업 설명
Memo editor 모듈화 및 각 메모 노드 단위로 택스트 수정 기능 추가

### ✅ To-do

- [x] Memo B/I/U 버튼을 통한 텍스트 스타일 적용 구현
- [x] Memo 생성 캡슐화 (Component으로 구분)
- [x] Memo  메모 노드 단위로 택스트 수정 기능 추가
