### ISSUE TITLE
✨ Feat: Vemo페이지 플레이리스트 설계 및 기능 구현

### ISSUE THREAD

**Issue by seongjin0614** [vemo-kj/vemo#40]
## 💼 작업 설명
vemo 페이지의 플레이리스트 설계 및 기능 구현

## ✅ To-do

- [x] vemo 페이지에서 플레이리스트 부분 작성
- [x] 플레이리스트 부분 기능 구현
- [x] API 통신 설계
- [ ] Dummy data test

**Comment by seongjin0614** [comment]
mvp test를 위한 통합 과정에서 merge
