### ISSUE TITLE
🔨 Refactor:  summary 부분 코드 추가 및 리팩토링

### ISSUE THREAD

**Issue by jerry-1211** [vemo-kj/vemo#41]
## 💼 작업 설명
- 요약 및 퀴즈 API 생성 및 정리

## ✅ To-do
- [x] 자막 받아오기
- [x] 유튜브 자막 요약하기 
- [x] 하드 코딩 한 부분 코드 리팩토링
- [x] 퀴즈 프롬프트 수정
- [x] 퀴즈 DB 저장
