### ISSUE TITLE
✨ Feat: Vemo 전체 캡처 / 부분 캡처 구현

### ISSUE THREAD

**Issue by daniely7** [vemo-kj/vemo#44]
## 💼 작업 설명
Vemo page의 전체 캡처 부분 캡처 구현

## ✅ To-do

- [x] 전체 캡처 구현
- [x] 부분 캡처 구현
- [x] 타임 스탬프와 연동
