### ISSUE TITLE
✨ Feat: Vemo page 그리기 기능 구현

### ISSUE THREAD

**Issue by daniely7** [vemo-kj/vemo#45]
### 💼 작업 설명
Vemo page 그리기 구현

### ✅ To-do

- [x] 캡처된 화면에서 그리기 구현
- [x] 그리기 팝업창으로 띄워서 적용하는 부분 구현
- [x] 그리기 구현 저장
